jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          command: >
            echo "The command above installs Heroku, the command below deploys.
            What you do inbetween is up to you!"
      - heroku/deploy-via-git
version: 2.1
orbs:
  heroku: circleci/heroku@1.2.5
workflows:
  heroku_deploy:
    jobs:
      - deploy